# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee8522a7a584d71783242e2c104e6b4948626483a900f3d3ce7f5b914e978eca4fcd4aca1750ae885454008b02ccc3a3d31dfbbc4e1dfd2f8eaddb612379a44

test:
  secret_key_base: 6bb10209b63fadd3cbd7bb01de901937415053e9e169d6cf90ba6139a53b5ee2c5713b735ccfd6eb21e26fd5561ed5ec407bc252d2e95262de7b3129c30fbbe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
